services:
  sigproc:
    build: .
    image: sigproc
    volumes:
      - type: bind
        source: ./src
        target: /home/anon/src
      - type: bind
        source: ./fonts
        target: /home/anon/.fonts
      - type: bind
        source: ./styles
        target: /home/anon/texmf/tex/latex
      - type: volume
        source: luatex-cache
        target: /var/cache/texmf-cache
      - type: volume
        source: virtualenvs
        target: /home/anon/.local/share/virtualenvs
volumes:
  luatex-cache:
  virtualenvs:
